Index: Makefile
===================================================================
--- Makefile	(revision 5455)
+++ Makefile	(working copy)
@@ -259,7 +259,7 @@
 REV:=$(RELEASE)
 else
 ifeq ($(shell if test -d .svn; then echo 1; fi), 1)
-REV_MODIFIED := $(shell svnversion . | grep -o M)
+REV_MODIFIED := $(shell svnversion . | sed -n 's/.*\(M\).*/\1/p' )
 REV := $(shell LC_ALL=C svn info | awk '/^URL:.*branch/ { BRANCH="-"a[split($$2, a, "/")] } /^Last Changed Rev:/ { REV="r"$$4"$(REV_MODIFIED)" } END { print REV BRANCH }')
 endif
 endif
